### ISSUE TITLE
Question 10 Discussion (Spoilers)

### ISSUE THREAD

**Issue by printablealice** [printablealice/a4#1]
**NOTE:** For assignment 4, please feel free to discuss with your classmates (on Github or elsewhere) any and all problems, just so long as your final code and written answers are written and understood by you.  **This thread will contain spoilers, and I recommend first trying the challenge problem on your own** 👍 Once you see the answer it may seem obvious, but figuring it out for the first time can still be quite tricky.

**NOTE:** Solution to a3 Question 12: https://github.com/printablealice/a3/issues/13

**Comment by nkueng** [comment]
Guess I have to get the discussion going here 😅 

My current performance on Q10 looks like this:
![Q10](https://user-images.githubusercontent.com/32466285/80726597-e5d08700-8b04-11ea-89e1-4eb147d2135e.gif)

Quite good, but far from perfect. Now the question is, how to improve my result?

Without giving too much away (Jim, let me know if I am allowed to provide more details without spoiling the assignment), I am currently optimizing 3 objectives:

- the final **position** 
- the **direction** of the final **velocity** 
- the **magnitude** of the  final **velocity** 

I am quite sure this approach satisfies all conditions to fly on a perfect circle – in theory. In practice, though, it seems there's still something missing.

Looking forward to hearing how other people have approached this and what their results were!

**Comment by printablealice** [comment]
Dope! My policy is you guys can discuss literally anything 🙂👍 I've added a spoilers tag so if people want to give it a shot on their own first they have that opportunity 👌

**Comment by nkueng** [comment]
@printablealice, thanks for the insight :) So, are you saying you had tweaked the integrator you showed in the video?

**Comment by printablealice** [comment]
> @printablealice, thanks for the insight :) So, are you saying you had tweaked the integrator you showed in the video?

Oh no no no, whoops that was unclear. There is still an answer that is perfect and uses the integrator I gave you :) (The code in the video is exactly what I gave you, only I added some lines to `evaluate()`.)

**Comment by nkueng** [comment]
But does it incorporate knowledge about the imperfection of the integration scheme?

On 30 Apr 2020, at 19:33, James Bern <notifications@github.com> wrote:

﻿

@printablealice<https://github.com/printablealice>, thanks for the insight :) So, are you saying you had tweaked the integrator you showed in the video?

Oh no no no, whoops that was unclear. There is still an answer that is perfect and uses the integrator I gave you :) (The code in the video is exactly what I gave you, only I added some lines to evaluate().)

**Comment by printablealice** [comment]
I think the answer to your question is technically yes, but I that may be
misleading. You can definitely implement my answer without knowing anything
at all about semi-implicit Euler, and the exact same answer should work for
a variety of other integration schemes.

**Comment by nkueng** [comment]
> "do you as the programmer need to personally know anything about the integration scheme?"

That's what I wanted to know, thanks!

**Comment by chaofiber** [comment]
Hello, I am quite curious why in the writeup the spaceship rotates the sun anticlockwise. Because that apparently means "consuming" more energy, which might not be good if our goal is just rotate around the sun (clockwise or anticlockwise).

And also when I set the objective with the same idea as @nkueng , the default orbit is anticlockwise. So my confusion would be two-folded. What is the advantage of anticlock orbit and how can we do that? I have a feeling with larger input would be the key to a ~perfect orbit tracking.. :)

**Comment by printablealice** [comment]
Hey! :) These are great questions and get at a really important idea in nonconvex optimization (local minima).  

> Hello, I am quite curious why in the writeup the spaceship rotates the sun anticlockwise.

I'm pretty sure it's just the local minimum the optimizer happened to find with my objective.  I wouldn't focus on it too much.  I am fairly certain if I played with my objective for a couple minutes I could get it to orbit the other direction.

> Because that apparently means "consuming" more energy, which might not be good if our goal is just rotate around the sun (clockwise or anticlockwise).

This is a bit of a toy problem, so things are maybe not quite as you'd expect them to be.  The ship can exert arbitrary force (`F_thrusters` unbounded) until `K = 32`, at which point `u <- 0` forever after.  So it doesn't really matter how much energy you consume.

> And also when I set the objective with the same idea as @nkueng , the default orbit is anticlockwise. So my confusion would be two-folded. 

Note that there really isn't such a thing as the "default orbit".  It's just the local minimum your particular optimizer happened to find optimizing your particular objective from your particular initial guess.  It's not fundamental.

> What is the advantage of anticlock orbit and how can we do that?

None that I know of.  Easiest way would be to hold your laptop up to a mirror :P 

> I have a feeling with larger input would be the key to a ~perfect orbit tracking.. :)

Mmm...I think I maybe don't fully understand this idea.  I would say probably not?

**Comment by chaofiber** [comment]
> Hey! :) These are great questions and get at a really important idea in nonconvex optimization (local minima).
> 
> > Hello, I am quite curious why in the writeup the spaceship rotates the sun anticlockwise.
> 
> I'm pretty sure it's just the local minimum the optimizer happened to find with my objective. I wouldn't focus on it too much. I am fairly certain if I played with my objective for a couple minutes I could get it to orbit the other direction.
> 
> > Because that apparently means "consuming" more energy, which might not be good if our goal is just rotate around the sun (clockwise or anticlockwise).
> 
> This is a bit of a toy problem, so things are maybe not quite as you'd expect them to be. The ship can exert arbitrary force (`F_thrusters` unbounded) until `K = 32`, at which point `u <- 0` forever after. So it doesn't really matter how much energy you consume.
> 
> > And also when I set the objective with the same idea as @nkueng , the default orbit is anticlockwise. So my confusion would be two-folded.
> 
> Note that there really isn't such a thing as the "default orbit". It's just the local minimum your particular optimizer happened to find optimizing your particular objective from your particular initial guess. It's not fundamental.
> 
> > What is the advantage of anticlock orbit and how can we do that?
> 
> None that I know of. Easiest way would be to hold your laptop up to a mirror :P
> 
> > I have a feeling with larger input would be the key to a ~perfect orbit tracking.. :)
> 
> Mmm...I think I maybe don't fully understand this idea. I would say probably not?

Aha Thanks for your answer. Then I know I am going to find a mirror and look from the reflection:) just joking:) Your answer is helpful !

**Comment by gitmon** [comment]
Hey guys, I think I got it! My idea was that if {xk, vk} have the correct orbital parameters, so should the next state: {xk1, vk1}. So in addition to the constraints mentioned above, I shot one step forward from {xk, vk} using the integrator, and then added constraints so that {xk1, vk1} would retain the correct orbital distance and speed. 

I believe this also forces the optimization to account for peculiarities in the integration scheme automatically, resulting in a (closer to) circular trajectory. Let me know what you all think. :)

**Comment by chaofiber** [comment]
> Hey guys, I think I got it! My idea was that if {xk, vk} have the correct orbital parameters, so should the next state: {xk1, vk1}. So in addition to the constraints mentioned above, I shot one step forward from {xk, vk} using the integrator, and then added constraints so that {xk1, vk1} would retain the same orbital distance and speed as {xk,vk}.
> 
> I believe this also forces the optimization to account for peculiarities in the integration scheme automatically, resulting in a (closer to) circular trajectory. Let me know what you all think. :)

I do think it is a good idea, and we might be able to make it even further by utilizing model predictive control ideas.

**Comment by printablealice** [comment]
> Hey guys, I think I got it! My idea was that if {xk, vk} have the correct orbital parameters, so should the next state: {xk1, vk1}. So in addition to the constraints mentioned above, I shot one step forward from {xk, vk} using the integrator, and then added constraints so that {xk1, vk1} would retain the same orbital distance and speed as {xk,vk}.
> 
> I believe this also forces the optimization to account for peculiarities in the integration scheme automatically, resulting in a (closer to) circular trajectory. Let me know what you all think. :)

Solid idea!  Note that there are many possible answers that are quite good.  I would say there is still a more elegant (in my opinion) answer out there, but don't feel any pressure to find it :P

**Comment by eastskykang** [comment]
In my opinion, considering there's no input or state constraint at all, this problem is really nothing but same with problem.4 (we can always guarantee that given certain target position and target velocity at time K, the orbiter would be enter and circulate around the sun), although the optimization problem is the form of [least square with regularization term (or ridge regression)](https://en.wikipedia.org/wiki/Tikhonov_regularization) anymore (since implicit Euler scheme does not end up with the linear system)

**Comment by eastskykang** [comment]
I'd add one more comment here, all we need to make sure is that there's only one constraint between x_K, v_K (position and velocity at time K resp.). So we can actually just give the objective forcing this constraint (so even no fixed target position and target velocity is required) but in this case, the optimization problem would not be convex anymore, so our GD optimization would be a bit unstable (I guess...? not tried though. But still it wouldn't be a big problem to converge to *some* local optimal solution)

**Comment by printablealice** [comment]
> I'd add one more comment here, all we need to make sure is that there's only one constraint between x_K, v_K (position and velocity at time K resp.).

I think the problem you will run into with this approach is that you really don't know what x_K, v_K should be.  You can try using the definition of centripetal force equation from Newtonian physics, but it won't really work so well due to the error in the integrator.

**Comment by eastskykang** [comment]
Thanks to Jim's feedback, I'd like to share some idea here, 

So naive approach kinda works but apparently not very good: giving target position as some point on the orbit, and its corresponding target velocity.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3031724/81022678-8066f800-8e6e-11ea-8e52-e5f346bbdbb6.gif)

So I added some 'knots' and optimize those knots' position and velocity some what like this, 

![Screenshot from 2020-05-05 01-29-28](https://user-images.githubusercontent.com/3031724/81023179-ec962b80-8e6f-11ea-9013-9ce67cd86be5.png)

and it's much better now :D 

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/3031724/81022759-bc01c200-8e6e-11ea-9021-00e1f848a3f1.gif)

**Comment by artyomskov** [comment]
![orbit](https://user-images.githubusercontent.com/37075917/81064630-4c292100-8eda-11ea-94c6-b06a9d3dd9c4.gif)

Hey guys, just wanted to share my approache since you helped me a lot in the past :)

Most success I had was by implementing a sort of model predictive controller that looks ahead in time, i.e. the controller takes into account of what's going to happen in the next, I dunno, 100 time steps _after_ K. This way you only have to impose constraints on the future states and won't get much trouble from the time integration.

Hope this helps.

Best, 
Leo

**Comment by aunagar** [comment]
Hi Everyone,
I have a question. In my current approach I put a condition on orbital distance, orbital velocity being perpendicular, and final thrust is 0 so that we remain in orbit forever. However, with this skim, my optimizer only optimize thrust for the last time-step. (ie. all other thrust are 0) and it puts satellite in the original orbit (with radius = 1), just a bit more perfectly.

Now, to make sure I put satellite in the orbit with 0.5 radius, I increased the weight of the orbital distance loss. But this mess up the trajectory completely. So, I wanted to know what kind of loss you are using in your objective function. And more specifically, are you using constraint only on last time-step (i.e. 32nd frame) or you are putting constraints everywhere?

Thanks.

**Comment by souryavarenya** [comment]
My solution still has the same essence as @nkueng 's approach (3 basic costs)  but did a couple of tweaks:
- Gave these different weights
- Constrained last 5 points of the trajectory to the above 3 rules
Still takes a little while to get on the right orbit but works decently. Also, for some reason, it chooses clockwise for me.
![a4q10](https://user-images.githubusercontent.com/12588291/81145450-9b249400-8f76-11ea-880e-14c0ac77f29f.gif)

**Comment by souryavarenya** [comment]
@aunagar Have you also included orbital velocity magnitude? Also, make sure all your costs are quadratic - absolute values didn't work for me for some reason.

**Comment by aunagar** [comment]
> @aunagar Have you also included orbital velocity magnitude constraint? Also, make sure all your costs are quadratic - absolute values didn't work for me for some reason.

Thank! I was using absolute deviance. Changing it to squared norm works now. That's weird. Why absolute deviance is not working?

**Comment by eastskykang** [comment]
> > @aunagar Have you also included orbital velocity magnitude constraint? Also, make sure all your costs are quadratic - absolute values didn't work for me for some reason.
> 
> Thank! I was using absolute deviance. Changing it to squared norm works now. That's weird. Why absolute deviance is not working?

In general, "vanilla" L-1 norm cost is avoided because it's not differentiable at the optimal point and can makes some nemerical unstability. Would this be the case for you? 

There's tones of tricks to solve this problem, like using huber-norm instead.

**Comment by printablealice** [comment]
> > @aunagar Have you also included orbital velocity magnitude constraint? Also, make sure all your costs are quadratic - absolute values didn't work for me for some reason.
> 
> Thank! I was using absolute deviance. Changing it to squared norm works now. That's weird. Why absolute deviance is not working?

In general for generic (not deep learning) optimization, you should always try a squared norm (L2) first.  With an absolute norm (L1) you will encounter the problem @eastskykang mentioned 👍
