### ISSUE TITLE
Deadline 1200 p.m.?

### ISSUE THREAD

**Issue by artyomskov** [printablealice/a4#10]
Hey, just wanted to ask what time the deadline is, since no time is specified and we have no exercise sessions.
Best, Leo

**Comment by printablealice** [comment]
I tried my best to specify it 11:59PM (the last possible moment on the
listed due date) 🙂👍
Let me know if there are any problems.
-Jim

**Comment by printablealice** [comment]
I think you can see the due date by clicking the original Github classroom
invitation link: https://classroom.github.com/a/EHZldrAM
(But on guarantees, as an instructor my interface may be different)
Best of luck!
Jim

**Comment by artyomskov** [comment]
Ah yeah, there it is on the github classroom!  Perfect. Thanks Jim!
Leo
