### ISSUE TITLE
Error in shooting app

### ISSUE THREAD

**Issue by sukhijab** [printablealice/a4#2]
Hi, I am getting an error in the shooting app (see picture)
<img width="1142" alt="Screenshot 2020-04-24 at 16 51 51" src="https://user-images.githubusercontent.com/61282968/80225927-09e72080-864c-11ea-8da5-6c6c1cd59e2c.png">

**Comment by printablealice** [comment]
Thanks for pointing that out!--Bugfix has been pushed, please confirm it works for you.

**Comment by sukhijab** [comment]
Should i pull my repository or where exactly has it been pushed, cause my repository has not been changed.

**Comment by printablealice** [comment]
Yeah you’ll have to pull. I can only change the main repo. Let me know if
it works! (Worst case you can just make the changes in the most recent
commit of the main repo manually, but pulling should work)

**Comment by sukhijab** [comment]
works now 👍
