### ISSUE TITLE
Q5

### ISSUE THREAD

**Issue by nkueng** [printablealice/a4#6]
I have troubles finding an adequate answer for Question 5:

> 5. Try optimizing for a few different targets with Newton’s method. _How many steps_ does Newton’s method usually take to converge for this problem? Why?

Coming up with a _qualitative_ answer to this question is less of a problem, however, you explicitly ask for a _quantitative_ answer. So my question is "how are we to evaluate this properly?". 

As far as I can tell, there's no (easily accessible) notion of time in the code that we could (ab)use to give us an indication of each solver's convergence time. The only (somewhat) quantitative tool I see at our disposal is the plot of `O(u_curr)` in the GUI. 

Thanks to the GUI, I could at least say "gradient descent converges really slowly while Newton usually takes one to a few timesteps".  But then comes the question:

> Why?

Here, I am also struggling to come up with a reasonable answer without digging too deep into the math behind the code. Does it suffice to say that "Newton knows which way to search for the minimum globally and GD only locally"? 

Thanks for clarifying a bit what exactly you expect from us here.

**Comment by printablealice** [comment]
Hey!

Oh that's fair, I could definitely have been more clear here.
You should also have a checkbox I've given you where you can print the current objective value.

```Checkbox("PRINT  O",  &PRINT_O);```

What I meant for you to try was the following (for shooting with no planet):
- with `OPTIMIZE` turned off set a target, and enable `PRINT_O`
- turn `OPTIMIZE` on and off
- look at the numerical values of the objective

If you try this a few times you should notice something interesting, and find an explanation. 

One thing I want to make sure on here is that I'm asking for the number of steps of Newton it takes to converge (i.e. the number of runs through process()).  I am _not_ asking for the amount of time in seconds.

Thanks for the question!--And let me know if it still isn't clear.

Best,
Jim

**Comment by nkueng** [comment]
Thanks, Jim! That helps tons :)

**Comment by printablealice** [comment]
HINT: Try working out what `x_3(u)`, i.e. "`x_3` as a function of `u=(u_0, u_1, u_2)`" is on a piece of paper (NOTE: there's nothing special about `x_3` in particular, but it should give you the idea of what's going on).

**Comment by eastskykang** [comment]
https://en.wikipedia.org/wiki/Tikhonov_regularization 

This may help. (so the objective has closed form solution, and it's exactly same with the solution by Newton optimization method)
