### ISSUE TITLE
Grading of Assignments: Individual Configuration

### ISSUE THREAD

**Issue by nkueng** [printablealice/a4#7]
Trying to tune my parameters for the optimizer, I realized there's a huge difference in the performance of the same parameters depending on the number of timesteps `K`. Since my machine couldn't provide fluid animations for the full 64 timestamps, I ran (and tuned) mine with 32 only. But if you are going to try my optimizer on 64 timesteps for evaluation, you might question my engineering skills. 

So, how will you go about grading for these exercises? Will you just run our code or will you do something more automated that might run into problems with individual configurations?

**Comment by printablealice** [comment]
I will grade on an individual basis 🙂👍 If your code works and produced
the screenshots you show me, then do not worry at all 👌

**Comment by nkueng** [comment]
@printablealice, just realized you're only asking for one screenshot in the assignment writeup (Q7). Do you want us to attach more than that?

**Comment by printablealice** [comment]
Oh shoot, yes that would be wonderful :) Please attach three screenshots,
one of shooting, one of transcription, and one of the challenge problem. I
will see if I can make an announcement to this effect.
